version: '3.8'
services:
  web:
    build: .
    image: php:8.1-apache
    ports:
      - "8080:80"  
    volumes:
      - .:/var/www/html  # Monte le dossier ./src dans le conteneur à l'emplacement où Apache servira les fichiers
      - ./templates:/var/www/html/templates  # Monte le dossier ./templates dans le conteneur à l'emplacement où Apache cherchera les templates Twig
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf  # Monte le fichier personnalisé de configuration du serveur Apache
    working_dir: /var/www/html  # Définit le répertoire de travail du conteneur pour que Composer et Apache y soient exécutés
    depends_on:
      - db
    

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=stageconnect
      - MYSQL_USER=user
      - PASSWORD=user123
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" # Accède à phpMyAdmin via http://localhost:8081
    environment:
      - PMA_HOST=db 
      - PMA_USER=root # Utilisateur MySQL
      - PMA_PASSWORD=root123 # Mot de passe MySQL
    depends_on:
      - db 

volumes:
  db_data:
